name: Build Firmware

on:
  push:
    branches:
      - eros_p2-userdebug-10-QP1A.191105.004-eng.chenza.20240613.193829-test-keys
  pull_request:
    branches:
      - eros_p2-userdebug-10-QP1A.191105.004-eng.chenza.20240613.193829-test-keys

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig simg2img

      - name: Sync Android Source
        run: |
          mkdir -p android
          cd android
          repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r1
          repo sync

      - name: Clone Device Tree
        run: |
          cd android/device/allwinner
          git clone https://github.com/torvalds/linux.git
          cp -r linux/arch/arm64/boot/dts/allwinner/sun50i-h313-tanix-tx1.dts android/device/allwinner/sun50i-h313-tanix-tx1.dts
          cd ../../..

      - name: Copy Prebuilt Files
        run: |
          cp prebuilt/dtb.img out/target/product/h313/dtb.img
          cp prebuilt/kernel out/target/product/h313/kernel

      - name: Build Recovery Image
        run: |
          source build/envsetup.sh
          lunch omni_h313-userdebug
          make -j$(nproc) recoveryimage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-firmware
          path: out/target/product/h313/recovery.img
